export enum DocumentPurpose {
  // Personal Documents
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  ID_DOCUMENT = 'ID_DOCUMENT',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  LICENSE = 'LICENSE',

  // Vehicle-related Documents
  VEHICLE_REGISTRATION = 'VEHICLE_REGISTRATION',
  VEHICLE_INSURANCE = 'VEHICLE_INSURANCE',
  VEHICLE_INSPECTION_REPORT = 'VEHICLE_INSPECTION_REPORT',
  VEHICLE_PHOTO = 'VEHICLE_PHOTO',
  ROADWORTHY_CERTIFICATE = 'ROADWORTHY_CERTIFICATE',

  // Business-related Documents
  BUSINESS_REGISTRATION_CERTIFICATE = 'BUSINESS_REGISTRATION_CERTIFICATE',
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',
  TAX_CLEARANCE_CERTIFICATE = 'TAX_CLEARANCE_CERTIFICATE',
  COMPANY_PROFILE = 'COMPANY_PROFILE',
  COMPANY_LOGO = 'COMPANY_LOGO',
  BUSINESS_ADDRESS_PROOF = 'BUSINESS_ADDRESS_PROOF',

  // Campaign-related Media
  CAMPAIGN_VIDEO = 'CAMPAIGN_VIDEO',
  CAMPAIGN_PICTURE = 'CAMPAIGN_PICTURE',

  // Miscellaneous
  OTHER = 'OTHER'
}